/*
Name: Ariel Ong (arielong@my.unt.edu)
Professor Shrestha
Date: 9 -27 - 2020
Description:This program will give you outputs based on the menu number you choose. If you choose "GREETING," it will access your time of day and use it to write a greeting. If you choose "WEATHER," the computer will output a random temperature in fahrenheit and whether it will be sunny or rainy. If you choose "GAME," the computer will play a guess game with you, where the chosen number is randomly generated by the computer. If you choose "EXIT," you will exit the program.
Parameters: Username, numbers guessed
Return: greeting, temperature, weather, number computer chose
*/ 

#include <iostream>
#include <string>
#include <time.h>
#include <ctime>
#include <cstdlib> 
using namespace std;

int main() {

	cout << "   Computer Science and Engineering" << endl << endl; 		//Output heading
	cout << "    CSCE 1030 - Computer Science I" << endl << endl;
	cout << "Ariel Ong  aco0078 arielong@my.unt.edu" << endl << endl;


	string username;							  //declaring username as string; username is variable name for user's full name

	cout << "Please enter your full name: ";				 //Prompting for user's full name
	getline (cin, username);

	int menuChoice = 0;
	
	enum MenuService {GREETING = 1, WEATHER = 2, GAME = 3, EXIT = 4 };


	do
	{
	cout << endl;
	cout << "Personal Concierge App: Choose a Service:" << endl; 			//this block of code will display the menu
        cout << "       1. Display Personal Greeting"<< endl;
        cout << "       2. Display Today's Weather Forecast"<< endl;
        cout << "       3. Play a Guessing Game"<< endl;
        cout << "       4. Exit"<< endl;

	cout << endl;                            		//endl for aesthetic reasons
        cout << "Enter service number wanted: ";   		//prompting for service number wanted
        cin >> menuChoice;					// prompting for menu choice
	cout << endl;						//endl for aesthetic reasons
	

	static_cast <MenuService>(menuChoice);   		//in order to use menuChoice for switch statement
	
	switch (menuChoice) {					//switch statement for the menu
	
		case GREETING:                 			//When user types "1"
			{                                       //bracket so that the computer understands these variables are limited to this case statement
			time_t rawtime;        			 //following block obtains the time that the user is using the program
		        string time_str;
       			rawtime = time(&rawtime);
       			time_str = ctime(&rawtime);
       			int time_hour;				//after parsing time_str for hour, store as integer so it can be used later
			
			cout << time_str;     										  //print out time user uses the program
			time_hour = stoi(time_str.substr(11,2)); 							//parsing the time_str for hour
			                         
			if (time_hour >= 0 && time_hour < 12 ){ 							//if statement to determine what time of day it is (12-11:59 am)
					cout << "Good morning, " << username << ". Have a nice day!" << endl << endl;
					}		
			else if (time_hour >= 12 && time_hour < 18 ){ 						          //12-5:59 pm is afternoon time
				cout << "Good afternoon, " << username << ". Enjoy your afternoon!" << endl << endl;
			}	
			else {  											 //6-12 am is night time
				cout << "Good evening, " << username << ". Enjoy your evening!" << endl << endl;
			}
			}
			break;

		case WEATHER:                 //When user types "2"
			{                     //bracket so that the computer understands that these variables are limited to this case statement
			int fahrenheit;       //declaring fahrenheit as integer
			fahrenheit = (rand() % 96) + 10; //setting range of numbers for fahrenheit

			if (fahrenheit >= 10 && fahrenheit <= 66){ //if fahrehneit is more than or equal to 10 ut less than or equal to 66, it will be rainy
				cout << "Today's forecast high of " << fahrenheit << " degrees and rainy." << endl;
			}
			else {     //if fahrenheit is more than 66, it will be sunny
				cout << "Today's forecast high of " << fahrenheit << " degrees and sunny." << endl;
			}
			}
			break;

		case GAME:      				 //When user types "3"
			{
			int chosenNum; 				 //declaring the number the computer will choose as chosenNum
			chosenNum = (rand() % 10) + 1; 	       	//setting range of numbers the computer can choose from
			int guess; 				 //this represents the user's guess
			int numGuess = 1;  			//is equal to the number of guesses

			cout << "You have three chances to guess my number from 1 to 10!" << endl << endl; //stating how many chances

			do{
				cout << "Guess #" << numGuess  << ": ";              //Stating what guess user is on
			       	cin >> guess;
				
				if (guess == chosenNum){
				cout << "Congrats in " << numGuess << " guesses! Good job!" << endl << endl;
				}	
				else if (guess > chosenNum) {
				cout << "Uh oh, your guess (" << guess << ") is too high! Guess a lower number." << endl << endl;
				numGuess++;
				}
				else {
				cout << "Oh no! Your guess (" << guess << ") is too low! Guess a higher number." << endl << endl;
				numGuess++;
				
				}
			}while ((guess != chosenNum) && (numGuess < 4));             //condition statement for loop
			
			if ((numGuess == 4) ){
				cout << "Sorry, my number was " << chosenNum << "!" << endl << endl;
			}
			}	
			break;
		case EXIT:                                                            //if user input is "4"
			cout << "You are now exiting the program, bye-bye! Have a nice day!" << endl << endl;  //Goodbye to user
			break;
	
		default:
			cout << "Error, enter another integer in between 1 - 4: "; 		//will take you back to the menu if wrong integer is entered 
			cin >> menuChoice; 		
			break;	
	
			}
	} while (menuChoice != 4); 			//will escape the program

	return 0;
}
